name: Build and Deploy to cf-page Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Skip Scripts Install ğŸ“¦
        run: npm i --skip-scripts  --loglevel=info

      - name: Install cross-fetch ğŸ“¦
        run: npm i cross-fetch  --loglevel=info

      - name: Install dependencies ğŸ“¦
        run: npm i  --loglevel=info

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Zip build folder ğŸ“¦
        run: zip -r build.zip ./build

      - name: Upload build artifact ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build.zip

      - name: Deploy to cf-page branch ğŸš€
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: cf-page
